# Site settings
title: "#BowtieFriday"
email: howdy@madebybowtie.com
description: > # this means to ignore newlines until "baseurl:"
  En podcast om att driva en liten app-studio i Stockholm, fast mest är vi två nördiga legobyggare som snackar högt och lågt om vad vi älskar att göra.
baseurl: "/podcast/" # the subpath of your site, e.g. /blog/
url: "http://madebybowtie.github.io" # the base hostname & protocol for your site
twitter_username: madebybowtie
#github_username:  jekyll

# Build settings
markdown: kramdown
